use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

// Expect a CSV with: OUI_HEX,vendor_name
// Example line: F4CE36,Apple
fn main() {
    println!("cargo:rerun-if-changed=data/oui.csv");

    let csv_path = PathBuf::from("data/oui.csv");
    let csv = fs::read_to_string(&csv_path)
        .expect("failed to read data/oui.csv (expected CSV: OUI_HEX,vendor_name)");

    let mut entries: Vec<(u32, String)> = Vec::new();

    for (i, line) in csv.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        // Split into 2 fields max (vendor names can contain commas if you want to allow that later)
        let mut parts = line.splitn(2, ',');
        let oui_hex = parts.next().unwrap().trim();
        let vendor = parts.next().unwrap_or("").trim();

        if oui_hex.len() != 6 {
            panic!(
                "data/oui.csv line {}: OUI must be 6 hex chars, got {:?}",
                i + 1,
                oui_hex
            );
        }

        let oui = u32::from_str_radix(oui_hex, 16)
            .unwrap_or_else(|_| panic!("data/oui.csv line {}: invalid hex {:?}", i + 1, oui_hex));

        // Escape vendor string for Rust source output
        let vendor_escaped = vendor.replace('\\', "\\\\").replace('"', "\\\"");
        entries.push((oui, vendor_escaped));
    }

    // Sort + dedup (keep last vendor name for duplicated OUI)
    entries.sort_by_key(|(k, _)| *k);
    entries.dedup_by_key(|(k, _)| *k);

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("vendor_map.rs");

    let mut out = String::new();
    out.push_str("// @generated by build.rs - DO NOT EDIT\n");
    out.push_str("pub static OUI_MAP: &[(u32, &str)] = &[\n");
    for (k, v) in entries {
        out.push_str(&format!("    (0x{:06X}, \"{}\"),\n", k, v));
    }
    out.push_str("];\n");

    let mut f = fs::File::create(&out_path).expect("failed to create generated vendor_map.rs");
    f.write_all(out.as_bytes())
        .expect("failed to write generated vendor_map.rs");
}
